@startuml

class User {
  username : String
  password : String
  email : String
  tokens: Decimal
}
User "1" --left-- "*" Message : author <
User "1" --down-- "*" Transaction : seller <
User "1" --down-- "*" Transaction : buyer <

class Offer {
    name: String
    description: String
    price: Decimal
}
Offer "0..1" --right-- "*" Transaction : about <
Offer "1" --right-- "*" User : offerer >

class CounterOffer extends Offer
CounterOffer "*" ---- "1" Offer : counters >

class ProductOffer extends Offer {}
class ServiceOffer extends Offer {}

class Request {
    name: String
    description: String
    price: Decimal
}
Request "0..1" --down-- "*" Transaction : about <
Request "1" --left-- "*" User : requester >

class ProductRequest extends Request {}
class ServiceRequest extends Request {}

class Transaction {
    status: Enum
    when: DateTime
    price: Decimal
}

class Admin extends User {}

class Message {
  when: DateTime
  text: String
}
Message "*" --right-- "1" Offer : for >

class Review {
    when: DateTime
    stars: Integer
    message: String
}
Review "*" --down-- "1" User : author >
Review "*" --down-- "1" User : about >


@enduml
