allowed-origins: "https://react-template.netlify.app,https://deploy-preview-*--react-template.netlify.app"

logging:
    level:
        org:
            hibernate: error
            springframework.core: error
            springframework.web: error
        root: error
